### ISSUE TITLE
Game Hub not responding if spirometer recording was skipped

### ISSUE THREAD

**Issue by cacarpe1** [CST316GroupC/asthma-game#3]
The recording screen currently skips itself if it has been done already which I think is calling the gamehub to fast causing it not to be able to run its update method. I suggest that the skipping should be done on the loginpage so it doesn't have to load a new screen and it would most likely fix the problem.

**Comment by dmierke** [comment]
I assume "recording screen" refers to the manual input page. It is currently linked to a text file that only accepts one recording per patient. Working on database to accept (or replace) inputs as well as date them.

**Comment by dchoffma** [comment]
Well the issue with the gamehub freezing was fixed, so i'll close down this issue.  If the database has an issue with the same page, I recommend making a new one and posting it there.
